
services:
  redis_cluster_creator:
    image: redis:8.0.3-alpine
    container_name: cluster_creator
    depends_on:
      - redis_1
      - redis_2
      - redis_3
    networks:
      - redis_network
    command: >
      sh -c "
      sleep 10 &&
      redis-cli --cluster create 
      192.168.3.11:6379 
      192.168.3.12:6379 
      192.168.3.13:6379 
      --cluster-replicas 0 --cluster-yes
      "
  redis_1:
    image: redis:8.0.3-alpine
    container_name: redis1
    ports:
      - "7001:6379"
      - "16371:16379"
    volumes:
      - redis_node_1:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --cluster-announce-ip 192.168.3.11 --cluster-announce-port 6379 --cluster-announce-bus-port 16379 --appendonly yes
    restart: always
    networks:
      redis_network:
        ipv4_address: 192.168.3.11

  
  redis_2:
    image: redis:8.0.3-alpine
    container_name: redis2
    ports:
      - "7002:6379"
      - "16372:16379"
    volumes:
      - redis_node_2:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --cluster-announce-ip 192.168.3.12 --cluster-announce-port 6379 --cluster-announce-bus-port 16379 --appendonly yes
    restart: always
    networks:
      redis_network:
        ipv4_address: 192.168.3.12

  redis_3:
    image: redis:8.0.3-alpine
    container_name: redis3
    ports:
      - "7003:6379"
      - "16373:16379"
    volumes:
      - redis_node_3:/data
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --cluster-announce-ip 192.168.3.13 --cluster-announce-port 6379 --cluster-announce-bus-port 16379 --appendonly yes
    restart: always
    networks:
      redis_network:
        ipv4_address: 192.168.3.13

volumes:
  redis_node_1:
    driver: local
  redis_node_2:
    driver: local
  redis_node_3:
    driver: local
  
networks:
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.1